# Generated by Django 6.0 on 2025-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefinder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingimage',
            name='image',
        ),
        migrations.AddField(
            model_name='housingimage',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='housing',
            table='housings',
        ),
        migrations.AlterModelTable(
            name='housingimage',
            table='images',
        ),
    ]
