# Generated by Django 6.0 on 2025-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefinder_app', '0002_remove_housingimage_image_housingimage_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('tenant', 'tenant'), ('admin', 'admin')], default='tenant', max_length=20),
        ),
    ]
