# Generated by Django 6.0 on 2025-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefinder_app', '0003_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('housing', 'author'), name='unique_housing_user'),
        ),
    ]
