# Generated by Django 6.0 on 2025-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefinder_app', '0005_alter_housing_price_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='housing_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room'), ('loft', 'Loft')], default='apartment', max_length=20),
        ),
    ]
